# -*- coding: utf-8 -*-
"""book_analyzer.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RkvOt9P_wfm7g2alif6Zi-xpHha4cWxP
"""

!pip install -q -U google-generativeai
import os
import google.generativeai as genai


os.environ["GOOGLE_API_KEY"] = "AIzaSyCQzNoZDfGu7DjG4-R2nAsc3eWv3un5X2k"
genai.configure(api_key=os.environ["GOOGLE_API_KEY"])

def analyze_with_gemini(passage):

    model = genai.GenerativeModel("gemini-2.5-flash")

    prompt = f"""
You are a helpful literature analysis assistant.

Read the following book passage carefully and give me the following details clearly and neatly:

1️ Total number of words in the passage
2️ The predominant emotion conveyed in the passage (like joy, sadness, hope, etc.)
3️ One possible famous book this passage could belong to (choose the closest one)
4️ A short summary of about 100 words describing the meaning of the passage
5️ The moral or key lesson of the passage in 1–2 lines

Here is the passage:
'''{passage}'''
"""


    response = model.generate_content(prompt)
    return response.text.strip()

# -Input -
passage = input("Enter your book passage:\n\n")

# - Run Analysis -
result = analyze_with_gemini(passage)
print("\n--- Analysis Result --- \n")
print(result)

